import {ImageSourcePropType} from 'react-native';

interface ImagePath {
  [key: string | number]: ImageSourcePropType | undefined;
  europe: ImageSourcePropType;
  europe2: ImageSourcePropType;
  europe3: ImageSourcePropType;
  europe4: ImageSourcePropType;
  europe5: ImageSourcePropType;
  adh01: ImageSourcePropType;
  bag: ImageSourcePropType;
  bag2: ImageSourcePropType;
  banklogo: ImageSourcePropType;
  basicprofile: ImageSourcePropType;
  camera: ImageSourcePropType;
  chat: ImageSourcePropType;
  curexchange: ImageSourcePropType;
  down: ImageSourcePropType;
  drag: ImageSourcePropType;
  euround: ImageSourcePropType;
  exchange: ImageSourcePropType;
  france: ImageSourcePropType;
  godown: ImageSourcePropType;
  goup: ImageSourcePropType;
  insurance: ImageSourcePropType;
  krround: ImageSourcePropType;
  leftarrow: ImageSourcePropType;
  lightning: ImageSourcePropType;
  logo: ImageSourcePropType;
  money: ImageSourcePropType;
  pay: ImageSourcePropType;
  plane: ImageSourcePropType;
  planning: ImageSourcePropType;
  profits: ImageSourcePropType;
  qrcode: ImageSourcePropType;
  remit: ImageSourcePropType;
  review: ImageSourcePropType;
  rightarrow: ImageSourcePropType;
  sagradafamilla: ImageSourcePropType;
  shopping: ImageSourcePropType;
  shopping2: ImageSourcePropType;
  sync: ImageSourcePropType;
  toggledown: ImageSourcePropType;
  trash: ImageSourcePropType;
  trip: ImageSourcePropType;
  ukround: ImageSourcePropType;
  up: ImageSourcePropType;
}

export const imagePath: ImagePath = {
  europe: require('./commercials/europe.jpg'),
  europe2: require('./commercials/europe2.jpg'),
  europe3: require('./commercials/europe3.jpg'),
  europe4: require('./commercials/europe4.jpg'),
  europe5: require('./commercials/europe5.jpg'),
  adh01: require('./adh01.png'),
  bag: require('./bag.jpg'),
  bag2: require('./bag2.png'),
  banklogo: require('./banklogo.png'),
  basicprofile: require('./basicprofile.png'),
  camera: require('./camera.png'),
  chat: require('./chat.png'),
  curexchange: require('./curexchange.png'),
  down: require('./down.png'),
  drag: require('./drag.png'),
  euround: require('./euround.png'),
  exchange: require('./exchange.png'),
  france: require('./france.png'),
  godown: require('./godown.png'),
  goup: require('./goup.png'),
  insurance: require('./insurance.png'),
  krround: require('./krround.png'),
  leftarrow: require('./leftarrow.png'),
  lightning: require('./lightning.png'),
  logo: require('./logo.png'),
  money: require('./money.png'),
  pay: require('./pay.png'),
  plane: require('./plane.png'),
  planning: require('./planning.png'),
  profits: require('./profits.png'),
  qrcode: require('./qrcode.png'),
  remit: require('./remit.png'),
  review: require('./review.jpg'),
  rightarrow: require('./rightarrow.png'),
  sagradafamilla: require('./sagradafamilia.png'),
  shopping: require('./shopping.png'),
  shopping2: require('./shopping2.jpg'),
  sync: require('./sync.png'),
  toggledown: require('./toggledown.png'),
  trash: require('./trash.png'),
  trip: require('./trip.png'),
  ukround: require('./ukround.png'),
  up: require('./up.png'),
};
